[project]
name = "reddit_qa_to_notion"
version = "0.1.0"
description = "Reddit Q&A to Notion MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.10.1",
    "praw>=7.8.1",
    "python-dotenv>=1.1.0",
    "requests>=2.32.4",
]
